import { Project, Task } from '@/types';
import { generateId } from './utils';

const now = new Date().toISOString();
const yesterday = new Date(Date.now() - 86400000).toISOString();
const tomorrow = new Date(Date.now() + 86400000).toISOString();
const nextWeek = new Date(Date.now() + 7 * 86400000).toISOString();

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-001',
    name: 'FlowBoard Web App',
    description: 'Build the next-gen project management tool with kanban, analytics, and real-time collaboration.',
    members: ['Alice Chen', 'Bob Smith', 'Carol Wu'],
    createdAt: yesterday,
  },
  {
    id: 'proj-002',
    name: 'Marketing Site Redesign',
    description: 'Revamp the company marketing site with new branding, improved performance, and accessibility.',
    members: ['Dave Lee', 'Eve Torres'],
    createdAt: yesterday,
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-001',
    projectId: 'proj-001',
    title: 'Set up authentication flow',
    description: 'Implement login and register pages with form validation and mock auth.',
    status: 'Done',
    priority: 'High',
    assignee: 'Alice Chen',
    dueDate: yesterday.split('T')[0],
    attachments: [],
    notes: '',
    subtasks: [
      { id: generateId(), title: 'Create login form', done: true },
      { id: generateId(), title: 'Add form validation', done: true },
      { id: generateId(), title: 'Connect to localStorage', done: true },
    ],
    comments: [],
    activity: [{ id: generateId(), message: 'Task created', createdAt: yesterday }],
    createdAt: yesterday,
    updatedAt: now,
  },
  {
    id: 'task-002',
    projectId: 'proj-001',
    title: 'Build Kanban board with DnD',
    description: 'Implement drag-and-drop kanban board using HTML5 native drag API.',
    status: 'In Progress',
    priority: 'Critical',
    assignee: 'Bob Smith',
    dueDate: tomorrow.split('T')[0],
    attachments: [],
    notes: '',
    subtasks: [
      { id: generateId(), title: 'Create KanbanColumn component', done: true },
      { id: generateId(), title: 'Add drag handlers', done: false },
      { id: generateId(), title: 'Persist status to localStorage', done: false },
    ],
    comments: [
      { id: generateId(), author: 'Alice Chen', text: 'Make sure to handle edge cases for empty columns.', createdAt: yesterday },
    ],
    activity: [{ id: generateId(), message: 'Task created', createdAt: yesterday }],
    createdAt: yesterday,
    updatedAt: now,
  },
  {
    id: 'task-003',
    projectId: 'proj-001',
    title: 'Canvas analytics chart',
    description: 'Draw a progress chart using raw Canvas 2D API — no chart libraries.',
    status: 'In Review',
    priority: 'Medium',
    assignee: 'Carol Wu',
    dueDate: nextWeek.split('T')[0],
    attachments: [],
    notes: 'Consider animating the bars on mount.',
    subtasks: [],
    comments: [],
    activity: [{ id: generateId(), message: 'Task created', createdAt: yesterday }],
    createdAt: yesterday,
    updatedAt: now,
  },
  {
    id: 'task-004',
    projectId: 'proj-001',
    title: 'Speech-to-text notes',
    description: 'Integrate Web Speech API for voice notes on the task detail page.',
    status: 'Backlog',
    priority: 'Low',
    assignee: 'Bob Smith',
    dueDate: nextWeek.split('T')[0],
    attachments: [],
    notes: '',
    subtasks: [],
    comments: [],
    activity: [{ id: generateId(), message: 'Task created', createdAt: yesterday }],
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: 'task-005',
    projectId: 'proj-002',
    title: 'Design new homepage hero',
    description: 'Create a bold hero section with animated headline and CTA.',
    status: 'In Progress',
    priority: 'High',
    assignee: 'Dave Lee',
    dueDate: tomorrow.split('T')[0],
    attachments: [],
    notes: '',
    subtasks: [
      { id: generateId(), title: 'Wireframe layout', done: true },
      { id: generateId(), title: 'Write copy', done: false },
    ],
    comments: [],
    activity: [{ id: generateId(), message: 'Task created', createdAt: yesterday }],
    createdAt: yesterday,
    updatedAt: now,
  },
  {
    id: 'task-006',
    projectId: 'proj-002',
    title: 'Accessibility audit',
    description: 'Run axe-core on all pages, fix WCAG AA violations.',
    status: 'Backlog',
    priority: 'Medium',
    assignee: 'Eve Torres',
    dueDate: nextWeek.split('T')[0],
    attachments: [],
    notes: '',
    subtasks: [],
    comments: [],
    activity: [{ id: generateId(), message: 'Task created', createdAt: yesterday }],
    createdAt: yesterday,
    updatedAt: yesterday,
  },
];
