/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/not-found`; params?: Router.UnknownInputParams; } | { pathname: `/page`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login/page` | `/login/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register/page` | `/register/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/layout` | `/layout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/dashboard/page` | `/dashboard/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/profile/page` | `/profile/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/projects/page` | `/projects/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/settings/page` | `/settings/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/projects/[id]/page` | `/projects/[id]/page`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(dashboard)'}/projects/[id]/tasks/[taskId]/page` | `/projects/[id]/tasks/[taskId]/page`, params: Router.UnknownInputParams & { id: string | number;taskId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/not-found`; params?: Router.UnknownOutputParams; } | { pathname: `/page`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login/page` | `/login/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register/page` | `/register/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/layout` | `/layout`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/dashboard/page` | `/dashboard/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/profile/page` | `/profile/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/projects/page` | `/projects/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/settings/page` | `/settings/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/projects/[id]/page` | `/projects/[id]/page`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(dashboard)'}/projects/[id]/tasks/[taskId]/page` | `/projects/[id]/tasks/[taskId]/page`, params: Router.UnknownOutputParams & { id: string;taskId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/layout${`?${string}` | `#${string}` | ''}` | `/not-found${`?${string}` | `#${string}` | ''}` | `/page${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login/page${`?${string}` | `#${string}` | ''}` | `/login/page${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register/page${`?${string}` | `#${string}` | ''}` | `/register/page${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/layout${`?${string}` | `#${string}` | ''}` | `/layout${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/dashboard/page${`?${string}` | `#${string}` | ''}` | `/dashboard/page${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/profile/page${`?${string}` | `#${string}` | ''}` | `/profile/page${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/projects/page${`?${string}` | `#${string}` | ''}` | `/projects/page${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/settings/page${`?${string}` | `#${string}` | ''}` | `/settings/page${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/not-found`; params?: Router.UnknownInputParams; } | { pathname: `/page`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login/page` | `/login/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register/page` | `/register/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/layout` | `/layout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/dashboard/page` | `/dashboard/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/profile/page` | `/profile/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/projects/page` | `/projects/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/settings/page` | `/settings/page`; params?: Router.UnknownInputParams; } | `${'/(dashboard)'}/projects/${Router.SingleRoutePart<T>}/page${`?${string}` | `#${string}` | ''}` | `/projects/${Router.SingleRoutePart<T>}/page${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/projects/${Router.SingleRoutePart<T>}/tasks/${Router.SingleRoutePart<T>}/page${`?${string}` | `#${string}` | ''}` | `/projects/${Router.SingleRoutePart<T>}/tasks/${Router.SingleRoutePart<T>}/page${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(dashboard)'}/projects/[id]/page` | `/projects/[id]/page`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(dashboard)'}/projects/[id]/tasks/[taskId]/page` | `/projects/[id]/tasks/[taskId]/page`, params: Router.UnknownInputParams & { id: string | number;taskId: string | number; } };
    }
  }
}
